[package]
name = "cert-get-core-ffi"
version = "0.1.0-alpha.1"
authors = ["Hugo Benício <hbobenicio@gmail.com>"]
edition = "2018"

[lib]
crate-type =["cdylib"]

[dependencies]
cert-get-core = { path = "../cert-get-core"}
