name: on-push-and-pull-request

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  tags-ignore:
    - '*'
env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --release

    - name: Run tests
      run: cargo test --release
      
