name: on-tag

on:
  push:
    tags:
      - master
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --release

    - name: Run tests
      run: cargo test --release

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2

    - name: Install cargo deb
      run: cargo install cargo-deb

    - name: Package DEB
      run: cargo deb -p cert-get-cli

    - name: Release
      uses: actions/upload-artifact@v2
      with:
        name: deb
        path: "target/debian/*.deb"
